#!/usr/bin/env python3
"""由 docs/specs/*.md 开头的单行 description 生成 Spec 索引；--check 只核对不写入。"""
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

SPEC_DIR = Path('docs/specs')
OUTPUT = SPEC_DIR / 'index.md'
HEADER = [
    '# Spec Index', '',
    'Generated by `python3 -B scripts/harness/spec_index.py`; edit descriptions in their source Specs.', '',
    '| Spec | Path | Description |', '| --- | --- | --- |',
]


def describe(path):
    lines = path.read_text(encoding='utf-8').splitlines()
    description = ''
    if lines and lines[0].strip() == '---':
        for line in lines[1:]:
            if line.strip() == '---':
                break
            match = re.match(r'^description:\s*(.*?)\s*$', line)
            if match:
                value = match[1]
                # 带双引号时按 JSON 字符串解析，兼容转义字符
                description = json.loads(value) if value.startswith('"') else value
                break
    if not description:
        sys.exit('Missing one-line YAML description: ' + path.as_posix())
    title = next((line[2:].strip() for line in lines if line.startswith('# ')), path.stem)
    return title, description


def build():
    rows = list(HEADER)
    for path in sorted(p for p in SPEC_DIR.glob('*.md') if p != OUTPUT):
        title, description = describe(path)
        title = title.replace('|', '\\|').replace('[', '\\[').replace(']', '\\]')
        rows.append('| [%s](%s) | %s | %s |' % (
            title, quote(path.name, safe='/-._~'), path.as_posix(), description.replace('|', '\\|')))
    return '\n'.join(rows) + '\n'


def main():
    generated = build()
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else None
    if '--check' in sys.argv[1:]:
        if current != generated:
            sys.exit('Spec index is stale; run python3 -B scripts/harness/spec_index.py')
        print('Spec index is current.')
    elif current != generated:
        OUTPUT.write_text(generated, encoding='utf-8')
        print('Generated ' + OUTPUT.as_posix())
    else:
        print('Spec index already current.')


if __name__ == '__main__':
    main()
